"""Tests for the emitter module."""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner

from speclord.cli import main
from speclord.emitter import emit


class TestEmitContent:
    def test_emit_includes_org_name(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "test-org" in content

    def test_emit_includes_stack(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "runtime=python" in content
        assert "language=python" in content

    def test_emit_includes_security_rules(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "Validate all input" in content
        assert "Never log credentials" in content

    def test_emit_includes_service_name(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "## Service: auth" in content

    def test_emit_includes_service_conventions(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "naming=snake_case" in content
        assert "error_handling=raise exceptions" in content

    def test_emit_includes_specs_table(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert "## Specs" in content
        assert "| File | Type | Status | Owner | Generates |" in content
        assert "api-endpoint" in content
        assert "handler" in content

    def test_emit_header_has_warning(self, valid_repo: Path) -> None:
        content = emit(valid_repo, "claude")
        assert content.startswith("# Project Constraints (generated by speclord)")
        assert "Do not edit manually" in content
        assert "speclord emit claude" in content

    def test_emit_no_org_still_works(self, tmp_path: Path) -> None:
        """Repo with no org spec still emits service/file content."""
        svc_dir = tmp_path / "pkg"
        svc_dir.mkdir()
        svc_spec = svc_dir / ".spec.yaml"
        svc_spec.write_text(
            'specVersion: "0.1.0"\n'
            'inherits: "org.spec.yaml"\n'
            'service: "my-svc"\n'
            'owner: "@team"\n'
        )
        content = emit(tmp_path, "claude")
        assert "Organization" not in content
        assert "## Service: my-svc" in content

    def test_emit_empty_repo(self, tmp_path: Path) -> None:
        """Repo with no specs produces minimal output."""
        content = emit(tmp_path, "claude")
        assert "# Project Constraints" in content
        assert "## Organization" not in content
        assert "## Service" not in content
        assert "## Specs" not in content

    def test_emit_target_in_header(self, valid_repo: Path) -> None:
        """Each target includes its own regeneration command."""
        for target in ("claude", "cursor", "copilot"):
            content = emit(valid_repo, target)
            assert f"speclord emit {target}" in content


class TestEmitCLI:
    def test_emit_claude_writes_file(self, valid_repo: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(main, ["emit", "claude", "--root", str(valid_repo)])
        assert result.exit_code == 0
        assert (valid_repo / "CLAUDE.md").exists()
        content = (valid_repo / "CLAUDE.md").read_text()
        assert "test-org" in content
        # Cleanup
        (valid_repo / "CLAUDE.md").unlink()

    def test_emit_cursor_writes_file(self, valid_repo: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(main, ["emit", "cursor", "--root", str(valid_repo)])
        assert result.exit_code == 0
        assert (valid_repo / ".cursorrules").exists()
        # Cleanup
        (valid_repo / ".cursorrules").unlink()

    def test_emit_copilot_writes_file(self, valid_repo: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(main, ["emit", "copilot", "--root", str(valid_repo)])
        assert result.exit_code == 0
        copilot = valid_repo / ".github" / "copilot-instructions.md"
        assert copilot.exists()
        # Cleanup
        copilot.unlink()
        (valid_repo / ".github").rmdir()

    def test_emit_all_writes_multiple(self, valid_repo: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(main, ["emit", "all", "--root", str(valid_repo)])
        assert result.exit_code == 0
        assert (valid_repo / "CLAUDE.md").exists()
        assert (valid_repo / ".cursorrules").exists()
        assert (valid_repo / ".github" / "copilot-instructions.md").exists()
        # Cleanup
        (valid_repo / "CLAUDE.md").unlink()
        (valid_repo / ".cursorrules").unlink()
        (valid_repo / ".github" / "copilot-instructions.md").unlink()
        (valid_repo / ".github").rmdir()

    def test_emit_dry_run_no_file(self, valid_repo: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(
            main, ["emit", "claude", "--root", str(valid_repo), "--dry-run"]
        )
        assert result.exit_code == 0
        assert "test-org" in result.output
        assert not (valid_repo / "CLAUDE.md").exists()
