"""Emitter — generates AI tool instruction files from the spec hierarchy."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from speclord.parser import (
    discover_specs,
    parse_file_spec,
    parse_org_spec,
    parse_service_spec,
)
from speclord.types import FileSpec, OrgSpec, ServiceSpec

# Target → output file mapping
TARGET_PATHS: dict[str, str] = {
    "claude": "CLAUDE.md",
    "cursor": ".cursorrules",
    "copilot": ".github/copilot-instructions.md",
}


def emit(root: Path, target: str) -> str:
    """Build the markdown content for a given AI tool target.

    Discovers all specs under root and assembles a project-wide
    instruction document suitable for the target AI tool.
    """
    return _build_content(root, target)


def output_path(root: Path, target: str) -> Path:
    """Return the output file path for a target."""
    return root / TARGET_PATHS[target]


def write_target(root: Path, target: str) -> Path:
    """Build content, write to disk, and return the output path."""
    content = emit(root, target)
    out = output_path(root, target)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return out


def _build_content(root: Path, target: str) -> str:
    """Shared content builder — assembles all spec layers into markdown."""
    org, services, files = _collect_specs(root)

    sections: list[str] = [_header(target)]

    if org is not None:
        sections.append(_format_org_section(org))

    for svc in services:
        sections.append(_format_service_section(svc))

    if files:
        sections.append(_format_specs_table(files, root))

    return "\n\n".join(sections) + "\n"


def _header(target: str) -> str:
    """Build the file header with auto-generation warning."""
    return (
        "# Project Constraints (generated by speclord)\n\n"
        "> Auto-generated from spec files. Do not edit manually.\n"
        f"> Re-generate with: `speclord emit {target}`"
    )


def _collect_specs(
    root: Path,
) -> tuple[OrgSpec | None, list[ServiceSpec], list[FileSpec]]:
    """Discover and parse all specs into categorized lists.

    The org spec is only read from the root directory (not subdirectories).
    """
    org: OrgSpec | None = None
    org_path = root / "org.spec.yaml"
    if org_path.exists():
        org = parse_org_spec(org_path)

    all_paths = discover_specs(root)
    services: list[ServiceSpec] = []
    files: list[FileSpec] = []

    # Skip bundled templates and test fixtures — they're not real project specs
    skip_dirs = {"templates", "fixtures"}

    for path in all_paths:
        if any(part in skip_dirs for part in path.relative_to(root).parts):
            continue
        if path.name == "org.spec.yaml":
            continue  # handled above — only root-level org spec
        elif path.name.endswith(".spec.yaml"):
            services.append(parse_service_spec(path))
        elif path.name.endswith(".spec.md"):
            files.append(parse_file_spec(path))

    return org, services, files


def _format_org_section(org: OrgSpec) -> str:
    """Format the organization section."""
    lines: list[str] = [f"## Organization: {org.organization}"]

    if org.stack:
        lines.append(f"- **Stack:** {_fmt_dict(org.stack)}")
    if org.patterns:
        lines.append(f"- **Patterns:** {_fmt_dict(org.patterns)}")
    if org.security:
        lines.append("- **Security:**")
        for rule in org.security:
            lines.append(f"  - {rule}")

    return "\n".join(lines)


def _format_service_section(svc: ServiceSpec) -> str:
    """Format a service section."""
    lines: list[str] = [f"## Service: {svc.service}"]

    lines.append(f"- **Owner:** {svc.owner}")
    if svc.conventions:
        lines.append(f"- **Conventions:** {_fmt_dict(svc.conventions)}")
    if svc.testing:
        lines.append(f"- **Testing:** {_fmt_dict(svc.testing)}")
    if svc.security:
        lines.append("- **Security:**")
        for rule in svc.security:
            lines.append(f"  - {rule}")

    return "\n".join(lines)


def _format_specs_table(specs: list[FileSpec], root: Path) -> str:
    """Format all file specs as a markdown table."""
    lines: list[str] = [
        "## Specs",
        "",
        "| File | Type | Status | Owner | Generates |",
        "|------|------|--------|-------|-----------|",
    ]

    for fs in specs:
        label = _spec_label(fs.file_path, root)
        generates = fs.generates or ""
        lines.append(f"| {label} | {fs.type} | {fs.status} | {fs.owner} | {generates} |")

    return "\n".join(lines)


def _spec_label(file_path: str, root: Path) -> str:
    """Compute a short label from a spec file path relative to root."""
    try:
        rel = Path(file_path).relative_to(root)
    except ValueError:
        rel = Path(file_path)

    label = rel.as_posix()
    if label.endswith(".spec.md"):
        label = label[: -len(".spec.md")]
    return label


def _fmt_dict(d: dict[str, Any]) -> str:
    """Render a dict as comma-separated key=value for display."""
    return ", ".join(f"{k}={v}" for k, v in d.items())
